### ISSUE TITLE
Reading data from ctx into yaml list does not work

### ISSUE THREAD

**Issue by gviciconte** [H2020-OpenModel/ExecFlow#4]
In a workflow, this is input step
```
steps:
  - workflow: execflow.oteapipipeline
  ....
    postprocess:
      - "{{ ctx.current.outputs['results']['input']|to_ctx('input') }}"
```

Reading variable from the ctx work perfectly if we want to assign to one entry
`density: "{{ ctx.input.density }}"`

but it is considered a string if we want to assign it as a list element 

```
density:
     - "{{ ctx.input.density }}"
```
meaning that in the second case density is equal to  `"{{ ctx.input.density }}"` instead of the float.
